spring:
  application:
    name: ms-cloud

#password will be hide
  datasource:
    url: jdbc:mysql://78.47.233.52:3306/cloud_lis_reports
    username: app_java_user_cloud
    password: GOr0dJU1x86KAV3T!-283@2
    hikari:
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: false

server:
  port: 8085

